### PR TITLE
Additional content for Element, Semigroup, Semiring

### PR DESCRIPTION
**Pull request by alex-a-levine**
Elements: Includes editing of documentation and unittests, and linting.

Semiring: Includes SemiringWithThreshold, TropicalMax/MinPlusSemiring, NaturalSemiring classes, together with documentation and unittests. Also includes linting of previous content.

CayleyGraph: Add CayleyGraph class to represent output of right/left_cayley_graph Semigroup functions, with member functions, documentation, unittests.

Semigroup: Finish unittests, linting, documentation. Add right_cayley_graph method, togther with documentation and unittests.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
So why are the tests failing @aal20?

**Comment by alex-a-levine** [comment]
It's the doctests. The Python 2 format for printing sets is set([a, b, ...]]), the Python 3 format is {a, b, ...}. So whichever format I use in the documentation, either the Python 2 or Python 3 tests will fail.

**Comment by james-d-mitchell** [comment]
Then maybe you can't use `set`s?

**Comment by alex-a-levine** [comment]
In the documentation only, or should I change the code itself. It works to use in both versions of python; it's only the different printing format that is causing the tests to fail.

**Comment by james-d-mitchell** [comment]
I'm not sure, what are you using a set for anyway?

**Comment by alex-a-levine** [comment]
To represent the strongly connected components of the right and left cayley graphs. Networkx gave them as a list of sets, with each set being an SCC. I saw no reason to change them, especially since checking set membership is fast.

**Comment by nthiery** [comment]
On Tue, Jun 20, 2017 at 02:02:30PM -0700, aal20 wrote:
>    To represent the strongly connected components of the right and left
>    cayley graphs. Networkx gave them as a list of sets, with each set
>    being an SCC. I saw no reason to change them, especially since checking
>    set membership is fast.

One way to handle this in doctests can be to use

    >>> f(...) == set([1,2,3])
    True

instead of

    >>> f(...)
    set([1,2,3])

Beside the question of difference in printing between Python 2 and 3,
it is also more robust (the order in which elements of a set are
printed can possibly vary).

Cheers,
                        Nicolas

**Comment by james-d-mitchell** [comment]
Good point @nthiery, thanks!

**Pull request closed without merging**
